- name: Check if the directory exists
  ansible.builtin.stat:
    path: /home/ec2-user/raisetech-live8-sample-app/.git
  register: git_directory

- name: Clone the specific branch
  ansible.builtin.git:
    repo: https://github.com/yuta-ushijima/raisetech-live8-sample-app.git
    dest: /home/ec2-user/raisetech-live8-sample-app
    version: main
  become: true
  when: not git_directory.stat.exists
  register: Clone_result

- name: Update the repository if it already exists
  ansible.builtin.git:
    repo: https://github.com/yuta-ushijima/raisetech-live8-sample-app.git
    dest: /home/ec2-user/raisetech-live8-sample-app
    version: main
    update: yes
  become: true
  when: git_directory.stat.exists
  register: Clone_result.changed



- name: change owner /var/www/raisetech-live8-sample-app
  become: yes
  file:
    path: "{{ sample_app_dir }}"
    state: directory
    owner: ec2-user
    recurse: yes
  when: git_clone.changed

- name: create database.yml
  become_user: root
  template:
    src: database.yml.j2
    dest: "{{ sample_app_dir }}/config/database.yml"

- name: create storage.yml
  become_user: root
  template:
    src: storage.yml.j2
    dest: "{{ sample_app_dir }}/config/storage.yml"

- name: edit unicorn.rb
  become_user: root
  template:
    src: unicorn.rb.j2
    dest: "{{ sample_app_dir }}/config/unicorn.rb"

- name: edit development.rb
  become_user: root
  template:
    src: development.rb.j2
    dest: "{{ sample_app_dir }}/config/environments/development.rb"
    
- name: edit puma.rb.j2
  become_user: root
  template:
    src: puma.rb.j2
    dest: "{{ sample_app_dir }}/config/puma.rb"