- name: Check if the directory exists
  ansible.builtin.stat:
    path: /home/ec2-user/raisetech-live8-sample-app/.git
  register: git_directory

- name: Clone the specific branch
  ansible.builtin.git:
    repo: https://github.com/yuta-ushijima/raisetech-live8-sample-app.git
    dest: /home/ec2-user/raisetech-live8-sample-app
    version: main
  become: true
  when: not git_directory.stat.exists
  register: Clone_result

- name: Change directory
  shell: cd raisetech-live8-sample-app

- name: add config/environments/development.rb
  become_user: root
  ansible.builtin.lineinfile:
    path: /home/ec2-user/raisetech-live8-sample-app/config/environments/development.rb
    insertbefore: config.action_controller.raise_on_missing_callback_actions = true
    firstmatch: yes
    line: config.hosts << "{{ aws_alb_host }}"

- name: add config/environments/production.rb
  become_user: root
  ansible.builtin.lineinfile:
    path: /home/ec2-user/raisetech-live8-sample-app/config/environments/production.rb
    insertbefore: config.action_controller.raise_on_missing_callback_actions = true
    firstmatch: yes
    line: config.hosts << "{{ aws_alb_host }}"

- name: add mini_magick to config/application.rb
  become_user: root
  ansible.builtin.lineinfile:
    path: /home/ec2-user/raisetech-live8-sample-app/config/application.rb
    insertbefore: config.generators.system_tests = nil
    firstmatch: yes
    line: config.active_storage.variant_processor = :mini_magick

- name: add mini_magick to config/application.rb
  become_user: root
  ansible.builtin.lineinfile:
    path: /home/ec2-user/raisetech-live8-sample-app/config/application.rb
    insertbefore: config.generators.system_tests = nil
    firstmatch: yes
    line: config.active_storage.variant_processor = :mini_magick


- name: Check if database.yml.sample exists
  stat:
    path: /home/ec2-user/raisetech-live8-sample-app/config/database.yml.sample
  register: file_check

- name: Rename database.yml.sample
  command: mv /home/ec2-user/raisetech-live8-sample-app/config/database.yml.sample /home/ec2-user/raisetech-live8-sample-app/config/database.yml
  when: file_check.stat.exists

- name: Render database.yml from template
  template:
    src: roles/08_app/templates/database.yml.j2
    dest: /home/ec2-user/raisetech-live8-sample-app/config/database.yml

- name: Ensure config directory exists
  file:
    path: "{{ sample_app_dir }}/config"
    state: directory

- name: create storage.yml
  become_user: root
  template:
    src: storage.yml.j2
    dest: "{{ sample_app_dir }}/config/storage.yml"

- name: Ensure environments directory exists
  file:
    path: "{{ sample_app_dir }}/config/environments"
    state: directory

- name: edit development.rb
  become_user: root
  template:
    src: development.rb.j2
    dest: "{{ sample_app_dir }}/config/environments/development.rb"
    
- name: edit puma.rb.j2
  become_user: root
  template:
    src: puma.rb.j2
    dest: "{{ sample_app_dir }}/config/puma.rb"