- name: check bundler install
  ansible.builtin.command: bash -lc "bundler version | grep {{ bundler_version }}"
  register: bundler_exists
  changed_when: no
  ignore_errors: true

- name: "install bundler {{ bundler_version }}"
  ansible.builtin.gem: 
    name: bundler
    version: "{{ bundler_version }}"
    user_install: no
  timeout: 300
  when: bundler_exists is failed