- name: Check if Bundler is installed
  stat:
    path: /home/ec2-user/.rbenv/versions/3.2.3/bin/bundle
  register: bundler_check

- name: Install Bundler
  become: yes
  become_user: ec2-user
  command: bash -lc "rbenv exec gem install bundler"
  when: not bundler_check.stat.exists