- name: Check if Bundler is installed
  stat:
    path: /home/ec2-user/.rbenv/versions/3.2.3/bin/bundle
  register: bundler_check

- name: Install Bundler
  command: bash -lc "gem install bundler"
  when: not bundler_check.stat.exists