# Install rvenv   
- name: install rbenv
  git: 
    repo: https://github.com/sstephenson/rbenv.git 
    dest: /home/ec2-user/.rbenv
  when: rbenv_installed is failed

- name: PATH for rbenv
  lineinfile: 
    path: /home/ec2-user/.bash_profile
    line: 'export PATH="$HOME/.rbenv/bin:$PATH"'
  when: rbenv_installed is failed

- name: eval rbenv init
  lineinfile: 
    path: /home/ec2-user/.bash_profile
    line: 'eval "$(rbenv init -)"'
  when: rbenv_installed is failed

- name: reflect .bash_profile
  shell: bash -lc "source ~/.bash_profile"
  when: rbenv_installed is failed

- name: install ruby-build
  git:
    repo: https://github.com/sstephenson/ruby-build.git
    dest: /home/ec2-user/.rbenv/plugins/ruby-build
  when: rbenv_installed is failed

# Install Ruby
- name: Check if Ruby is installed
  stat:
    path: /home/ec2-user/.rbenv/versions/3.2.3
  register: ruby_check

- name: Install Ruby 3.2.3
  shell: bash -lc "rbenv install 3.2.3"
  when: not ruby_check.stat.exists

- name: Rehash rbenv
  shell: bash -lc "rbenv rehash"

- name: Set global Ruby version to 3.2.3
  shell: bash -lc "rbenv global 3.2.3"


# Install Rails
- name: Check if Rails is installed
  shell: bash -lc "gem list -e rails | grep 7.1.3.2"
  register: rails_check
  changed_when: no
  ignore_errors: true

- name: Install Rails 7.1.3.2
  gem:
    name: rails
    version: 7.1.3.2
    user_install: no
    executable: /home/ec2-user/.rbenv/shims/gem
  when: rails_check is failed

# Install Bundler
- name: Check if Bundler is installed
  stat:
    path: /home/ec2-user/.rbenv/versions/3.2.3/bin/bundle
  register: bundler_check

- name: Install Bundler
  command: bash -lc "gem install bundler"