# Install rvenv   
- name: Clone anyenv repository
  ansible.builtin.git:
    repo: "https://github.com/anyenv/anyenv.git"
    dest: "/home/ec2-user/.anyenv"

- name: Install rbenv plugin
  ansible.builtin.git:
    repo: "https://github.com/rbenv/ruby-build.git"
    dest: "/home/ec2-user/.anyenv/plugins/ruby-build"

- name: Change ownership of .anyenv directory to ec2-user
  file:
    path: "/home/ec2-user/.anyenv"
    owner: ec2-user
    group: ec2-user
    recurse: yes
    state: directory

- name: Add .anyenv path to .bash_profile
  lineinfile:
    path: /home/ec2-user/.bash_profile
    line: 'export PATH="$HOME/.anyenv/bin:$PATH"'
    create: yes

- name: Initialize anyenv
  lineinfile:
    path: /home/ec2-user/.bash_profile
    line: 'eval "$(anyenv init -)"'
    create: yes

- name: Source bash_profile
  shell: source /home/ec2-user/.bash_profile

# test
- name: Initialize anyenv installation
  shell: anyenv install --init
# test

- name: Install rbenv
  shell: anyenv install rbenv

# Install Ruby
- name: Check if Ruby is installed
  stat:
    path: /home/ec2-user/.rbenv/versions/3.2.3
  register: ruby_check

- name: Install Ruby 3.2.3
  shell: bash -lc "rbenv install 3.2.3"
  when: not ruby_check.stat.exists

- name: Rehash rbenv
  shell: bash -lc "rbenv rehash"

- name: Set global Ruby version to 3.2.3
  shell: bash -lc "rbenv global 3.2.3"


# Install Rails
- name: Check if Rails is installed
  shell: bash -lc "gem list -e rails | grep 7.1.3.2"
  register: rails_check
  changed_when: no
  ignore_errors: true

- name: Install Rails 7.1.3.2
  gem:
    name: rails
    version: 7.1.3.2
    user_install: no
    executable: /home/ec2-user/.rbenv/shims/gem
  when: rails_check is failed

# Install Bundler
- name: Check if Bundler is installed
  stat:
    path: /home/ec2-user/.rbenv/versions/3.2.3/bin/bundle
  register: bundler_check

- name: Install Bundler
  command: bash -lc "gem install bundler"