# Install rvenv   
- name: Clone rbenv repository
  become_user: root
  git:
    repo: "https://github.com/sstephenson/rbenv.git"
    dest: "/home/ec2-user/.rbenv"
    version: master

- name: Change ownership of .rbenv directory to ec2-user
  become_user: root
  file:
    path: "/home/ec2-user/.rbenv"
    owner: ec2-user
    group: ec2-user
    recurse: yes
    state: directory

- name: Add rbenv path to .bashrc
  lineinfile:
    path: /home/ec2-user/.bashrc
    line: 'export PATH="$HOME/.rbenv/bin:$PATH"'
    create: yes

- name: Initialize rbenv
  lineinfile:
    path: /home/ec2-user/.bashrc
    line: 'eval "$(rbenv init -)"'
    create: yes

- name: Load .bash_profile
  shell: bash -lc "source /home/ec2-user/.bashrc"

- name: Install rbenv plugins
  git:
    repo: https://github.com/sstephenson/ruby-build.git
    dest: "/home/ec2-user/.rbenv/plugins/ruby-build"

# Install Ruby
- name: Check if Ruby is installed
  stat:
    path: /home/ec2-user/.rbenv/versions/3.2.3
  register: ruby_check

- name: Install Ruby 3.2.3
  shell: bash -lc "rbenv install 3.2.3"
  when: not ruby_check.stat.exists

- name: Rehash rbenv
  shell: bash -lc "rbenv rehash"

- name: Set global Ruby version to 3.2.3
  shell: bash -lc "rbenv global 3.2.3"


# Install Rails
- name: Check if Rails is installed
  shell: bash -lc "gem list -e rails | grep 7.1.3.2"
  register: rails_check
  changed_when: no
  ignore_errors: true

- name: Install Rails 7.1.3.2
  gem:
    name: rails
    version: 7.1.3.2
    user_install: no
    executable: /home/ec2-user/.rbenv/shims/gem
  when: rails_check is failed

# Install Bundler
- name: Check if Bundler is installed
  stat:
    path: /home/ec2-user/.rbenv/versions/3.2.3/bin/bundle
  register: bundler_check

- name: Install Bundler
  command: bash -lc "gem install bundler"