# Install rvenv
- name: Clone rbenv repository
  become_user: root
  ansible.builtin.git:
    repo: "https://github.com/sstephenson/rbenv.git"
    dest: "/home/ec2-user/.rbenv"

- name: Install rbenv plugin
  ansible.builtin.git:
    repo: "https://github.com/sstephenson/ruby-build.git"
    dest: "/home/ec2-user/.rbenv/plugins/ruby-build"

- name: Change ownership of .rbenv directory to ec2-user
  become_user: root
  file:
    path: "/home/ec2-user/.rbenv"
    owner: ec2-user
    group: ec2-user
    recurse: yes
    state: directory

- name: Add .rbenv path to .bash_profile
  become_user: ec2-user
  lineinfile:
    path: /home/ec2-user/.bash_profile
    line: 'export PATH="$HOME/.rbenv/bin:$PATH"'
    create: yes

- name: Initialize rbenv
  become_user: ec2-user
  lineinfile:
    path: /home/ec2-user/.bash_profile
    line: 'eval "$(rbenv init -)"'
    create: yes

- name: Source bash_profile
  become_user: ec2-user
  shell: source /home/ec2-user/.bash_profile

# Install Ruby
- name: Check if Ruby is installed
  become_user: ec2-user
  stat:
    path: /home/ec2-user/.rbenv/versions/3.2.3
  register: ruby_check

- name: Install Ruby 3.2.3
  become_user: ec2-user
  shell: bash -lc "rbenv install 3.2.3"
  when: not ruby_check.stat.exists

- name: Rehash rbenv
  become_user: ec2-user
  shell: bash -lc "rbenv rehash"

- name: Set global Ruby version to 3.2.3
  become_user: ec2-user
  shell: bash -lc "rbenv global 3.2.3"


# Install Rails
- name: Check if Rails is installed
  become_user: ec2-user
  shell: bash -lc "gem list -e rails | grep 7.1.3.2"
  register: rails_check
  changed_when: no
  ignore_errors: true

- name: Install Rails 7.1.3.2
  become_user: ec2-user
  gem:
    name: rails
    version: 7.1.3.2
    user_install: no
    executable: /home/ec2-user/.rbenv/shims/gem
  when: rails_check is failed

# Install Bundler
- name: Check if Bundler is installed
  become_user: ec2-user
  stat:
    path: /home/ec2-user/.rbenv/versions/3.2.3/bin/bundle
  register: bundler_check

- name: Install Bundler
  become_user: ec2-user
  command: bash -lc "gem install bundler"