- name: check rbenv install # rubyのバージョン管理ツールであるrbenvがインストールされているか確認
  shell: bash -lc "rbenv --version"
  register: rbenv_exists
  changed_when: no
  ignore_errors: yes # タスクがエラーになった場合でも、スクリプトの実行を中断せずに続行させる

- name: Install rbenv
  git:
    repo: https://github.com/sstephenson/rbenv.git
    dest: /home/ec2-user/.rbenv
  when: rbenv_exists is failed

- name: Add rbenv to PATH
  lineinfile: # ファイルないの特定の行に変更を加えるためのモジュール
    path: /home/ec2-user/.bash_profile
    line: 'export PATH="$HOME/.rbenv/bin:$PATH"'

- name: Enable shims and autocompletion for rbenv
  lineinfile:
    path: /home/ec2-user/.bash_profile
    line: 'eval "$(rbenv init -)"'

- name: Reload bash profile
  shell: source /home/ec2-user/.bash_profile

- name: Install ruby-build
  git:
    repo: https://github.com/sstephenson/ruby-build.git
    dest: /home/ec2-user/.rbenv/plugins/ruby-build


# Install Ruby
- name: Check if Ruby is installed
  stat:
    path: /home/ec2-user/.rbenv/versions/3.2.3
  register: ruby_check

- name: Install Ruby 3.2.3
  shell: bash -lc "rbenv install 3.2.3"
  when: not ruby_check.stat.exists

- name: Rehash rbenv
  shell: bash -lc "rbenv rehash"

- name: Set global Ruby version to 3.2.3
  shell: bash -lc "rbenv global 3.2.3"


# Install Rails
- name: Check if Rails is installed
  shell: bash -lc "gem list -e rails | grep 7.1.3.2"
  register: rails_check
  changed_when: no
  ignore_errors: true

- name: Install Rails 7.1.3.2
  gem:
    name: rails
    version: 7.1.3.2
    user_install: no
    executable: /home/ec2-user/.rbenv/shims/gem
  when: rails_check is failed

# Install Bundler
- name: Check if Bundler is installed
  stat:
    path: /home/ec2-user/.rbenv/versions/3.2.3/bin/bundle
  register: bundler_check

- name: Install Bundler
  command: bash -lc "gem install bundler"