- name: Clone rbenv repository
  git:
    repo: 'https://github.com/rbenv/rbenv.git'
    dest: /home/ec2-user/.rbenv
    version: master
  become_user: ec2-user

- name: Clone ruby-build repository
  git:
    repo: 'https://github.com/rbenv/ruby-build.git'
    dest: /home/ec2-user/.rbenv/plugins/ruby-build
    version: master
  become_user: ec2-user

- name: Add rbenv path to .bash_profile
  lineinfile:
    path: /home/ec2-user/.bash_profile
    line: 'export PATH="$HOME/.rbenv/bin:$PATH"'
    create: yes
  become_user: ec2-user

- name: Initialize rbenv
  lineinfile:
    path: /home/ec2-user/.bash_profile
    line: 'eval "$(rbenv init -)"'
    create: yes
  become_user: ec2-user

- name: Load .bash_profile
  shell: source /home/ec2-user/.bash_profile
  args:
    executable: /bin/bash
  become_user: ec2-user

- name: Install Ruby 3.2.3
  shell: /home/ec2-user/.rbenv/bin/rbenv install 3.2.3
  become_user: ec2-user

- name: Rehash rbenv
  shell: /home/ec2-user/.rbenv/bin/rbenv rehash
  become_user: ec2-user

- name: Set global Ruby version to 3.2.3
  shell: /home/ec2-user/.rbenv/bin/rbenv global 3.2.3
  become_user: ec2-user

- name: Check if Rails is installed
  shell: /home/ec2-user/.rbenv/shims/gem list -e rails | grep 7.1.3.2
  register: rails_check
  changed_when: no
  ignore_errors: true
  become_user: ec2-user

- name: Install Rails 7.1.3.2
  gem:
    name: rails
    version: 7.1.3.2
    user_install: no
    executable: /home/ec2-user/.rbenv/shims/gem
  when: rails_check is failed
  become_user: ec2-user

- name: Check if Bundler is installed
  stat:
    path: /home/ec2-user/.rbenv/versions/3.2.3/bin/bundle
  register: bundler_check
  become_user: ec2-user

- name: Install Bundler
  shell: /home/ec2-user/.rbenv/shims/gem install bundler
  become_user: ec2-user