# Install rvenv
- name: check rbenv install
  ansible.builtin.command: bash -lc "rbenv --version"
  # ansible.builtin.command: bash -lc "/home/ec2-user/.rbenv/bin/rbenv --version"
  register: rbenv_exists
  changed_when: no
  ignore_errors: true

- name: Install rbenv
  ansible.builtin.git:
    repo: https://github.com/sstephenson/rbenv.git
    dest: /home/ec2-user/.rbenv
  when: rbenv_exists is failed

- name: Add /home/ec2-user.rbenv/bin to PATH
  ansible.builtin.lineinfile:
    path: /home/ec2-user/.bashprofile
    line: export PATH=/home/ec2-user/.rbenv/bin:$PATH
    state: present
  when: rbenv_exists is failed

- name: Add /home/ec2-user.rbenv/bin to PATH 2
  ansible.builtin.lineinfile:
    path: /home/ec2-user/.bashprofile
    line: eval "$(rbenv init -)"
    state: present
  when: rbenv_exists is failed

- name: source /home/ec2-user/.bashprofile
  ansible.builtin.command: bash -lc "source /home/ec2-user/.bashprofile"
  when: rbenv_exists is failed
  changed_when: false

- name: Check if Ruby is installed
  stat:
    path: /home/ec2-user/.rbenv/versions/3.2.3
  register: ruby_check

- name: Install Ruby 3.2.3
  shell: bash -lc "rbenv install 3.2.3"
  when: not ruby_check.stat.exists

- name: Rehash rbenv
  shell: bash -lc "rbenv rehash"

- name: Set global Ruby version to 3.2.3
  shell: bash -lc "rbenv global 3.2.3"

# Install Rails
- name: Check if Rails is installed
  shell: bash -lc "gem list -e rails | grep 7.1.3.2"
  register: rails_check
  changed_when: no
  ignore_errors: true

- name: Install Rails 7.1.3.2
  gem:
    name: rails
    version: 7.1.3.2
    user_install: no
    executable: /home/ec2-user/.rbenv/shims/gem
  when: rails_check is failed

# Install Bundler
- name: Check if Bundler is installed
  stat:
    path: /home/ec2-user/.rbenv/versions/3.2.3/bin/bundle
  register: bundler_check

- name: Install Bundler
  command: bash -lc "gem install bundler"