version: 2.1

orbs:
  aws-cli: circleci/aws-cli@4.1.2

jobs:
  execute-cloud-formation:
    executor: aws-cli/default
    steps:
      - checkout
      - aws-cli/setup:
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
          aws-region: AWS_DEFAULT_REGION
      - run:
          name: Deploy cloudformation
          command: |
            set -x
            aws cloudformation deploy --template-file cloudformation/service.yml --stack-name sampleStack

workflows:
  RaiseTech:
    jobs:
      - execute-cloud-formation
