version: 2.1

orbs:
  aws-cli: circleci/aws-cli@4.1.2
  ansible-playbook: orbss/ansible-playbook@0.0.5
  ruby: circleci/ruby@2.1.1

jobs:
  execute-cloud-formation:
    executor: aws-cli/default
    steps:
      - checkout
      - aws-cli/setup:
          aws_access_key_id: AWS_ACCESS_KEY_ID
          aws_secret_access_key: AWS_SECRET_ACCESS_KEY
          region: AWS_DEFAULT_REGION
      - run:
          name: Deploy cloudformation
          command: |
            set -x
            aws cloudformation deploy --template-file cloudformation/service.yml --stack-name sample-Stack --parameter-overrides CIDRIP=10.0.0.0/24 Prefix=RaiseTech --capabilities CAPABILITY_IAM

  execute-ansible:
    executor: ansible-playbook/default
    circleci_ip_ranges: true
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - 'SHA256:ZcPWdzOE2zdPrzEERDYkmgBJAHZwQgBDS4ZLSRHYUvM'
      - ansible-playbook/install:
          version: 2.10.7
      - ansible-playbook/playbook:
          playbook: ansible/playbook.yml
          playbook-options: '-u ec2-user -i ansible/inventory'

  execute-serverspec:
    executor: ruby/default
    circleci_ip_ranges: true
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - 'SHA256:pnpKfoKDXiSeE2egoHIZbe02OKvlhu+fVoiLgxEDhf0'
      - ruby/install:
          version: '3.1.2'
      - ruby/install-deps:
          app-dir: serverspec
      - run:
          name: 'execute serverspec'
          command: |
            cd serverspec
            bundle exec rspec

workflows:
  RaiseTech:
    jobs:
      - execute-cloud-formation
      - execute-ansible:
          requires:
            - execute-cloud-formation
      - execute-serverspec:
          requires:
            - execute-ansible

