# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

orbs:
  aws-cli: circleci/aws-cli@4.1.2
  ansible-playbook: orbss/ansible-playbook@0.0.5
  ruby: circleci/ruby@2.1.1

jobs:
  test:
    docker:
      - image: circleci/ruby:3.1.2
    steps:
      - checkout
      - run:
          name: Install Bundler
          command: gem install bundler -v 2.3.14
      - run:
          name: Install Rails
          command: gem install rails -v 7.1.3.2
      - run:
          name: Install Unicorn
          command: gem install unicorn
      - run:
          name: Start Unicorn
          command: bundle exec unicorn -c config/unicorn.rb -E production -D
      - run:
          name: Run Tests
          command: bundle exec rspec
          
  execute-ansible:
    executor: ansible-playbook/default
    steps:
      # Checkout the code as the first step.
      - checkout
      - add_ssh_keys:
          fingerprints:
            - '10:3a:69:ba:f3:55:2b:12:b4:58:2e:fb:7d:97:30:8c:93:09:73:ca'
      - ansible-playbook/install:
          version: 2.10.7
      - ansible-playbook/playbook:
          playbook: ansible/playbook.yml
          playbook-options: '-u ec2-user -i ansible/inventory'

  execute-serverspec:
    executor: ruby/default
    steps:
      - checkout
      - ruby/install:
          version: '3.2.3'
      - ruby/install-deps:
          app-dir: serverspec
      - run:
          name: 'execute serverspec'
          command: |
            cd serverspec
            bundle exec rspec

workflows:
  RaiseTech:
    jobs:
      - execute-ansible
      - execute-serverspec:
          requires:
            - execute-ansible
            
