version: 2.1

orbs:
  aws-cli: circleci/aws-cli@4.1.3
  ansible-playbook: orbss/ansible-playbook@0.0.5
  ruby: circleci/ruby@2.1.3

jobs:
  execute-cloud-formation:
    executor: aws-cli/default
    steps:
      - checkout
      - aws-cli/setup:
          aws_access_key_id: AWS_ACCESS_KEY_ID
          aws_secret_access_key: AWS_SECRET_ACCESS_KEY
          region: AWS_DEFAULT_REGION
      - run:
          name: Deploy cloudformation
          command: |
            set -x
            aws cloudformation deploy --template-file cloudformation/service.yml --stack-name sample-Stack --parameter-overrides CIDRIP=10.0.0.0/24 Prefix=RaiseTech --capabilities CAPABILITY_IAM

  execute-ansible:
    executor: ansible-playbook/default
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - '10:3a:69:ba:f3:55:2b:12:b4:58:2e:fb:7d:97:30:8c:93:09:73:ca'
      - ansible-playbook/install:
          version: 2.10.7
      - ansible-playbook/playbook:
          playbook: ansible/playbook.yml
          playbook-options: '-u ec2-user -i ansible/inventory'

      # Set permissions for log and tmp directories
      - run:
          name: Set permissions for log and tmp directories
          command: |
            touch /home/ec2-user/raisetech-live8-sample-app/log/development.log
            chmod 0664 /home/ec2-user/raisetech-live8-sample-app/log/development.log
            mkdir -p /home/ec2-user/raisetech-live8-sample-app/tmp/miniprofiler
            chmod -R 0775 /home/ec2-user/raisetech-live8-sample-app/tmp
      - run:
          name: Install dependencies
          command: bundle install
      - run:
          name: Setup database
          command: bin/setup

  execute-serverspec:
    executor: ruby/default
    steps:
      - checkout
      - ruby/install:
          version: '3.2.3'
      - ruby/install-deps:
          app-dir: serverspec
      - run:
          name: 'execute serverspec'
          command: |
            cd serverspec
            bundle exec rspec

workflows:
  RaiseTech:
    jobs:
      - execute-cloud-formation
      - execute-ansible:
          requires:
            - execute-cloud-formation
      - execute-serverspec:
          requires:
            - execute-ansible

