- name: Ensure Gemfile exists
  stat:
    path: "{{ sample_app_dir }}/Gemfile"
  register: gemfile_check

- name: Install gems
  shell: bash -lc "bundle install"
  args:
    chdir: "{{ sample_app_dir }}"
  become_user: ec2-user
  when: gemfile_check.stat.exists

- name: Check if rails is installed
  shell: bash -lc "gem list -e rails | grep {{ rails_version }}"
  register: check_rails_installed
  changed_when: no
  ignore_errors: yes
  environment:
    RBENV_ROOT: /home/ec2-user/.rbenv
    PATH: /home/ec2-user/.rbenv/bin:/home/ec2-user/.rbenv/shims:{{ ansible_env.PATH }}

- name: Initialize rbenv and install Bundler
  shell: |
    source /home/ec2-user/.bash_profile
    gem install bundler
  args:
    executable: /bin/bash
  become_user: ec2-user

- name: Check if Bundler is installed
  shell: |
    source /home/ec2-user/.bash_profile
    bundle -v
  register: check_bundler_installed
  ignore_errors: true
  args:
    executable: /bin/bash
  become_user: ec2-user

- name: Install Bundler if not present
  shell: |
    source /home/ec2-user/.bash_profile
    gem install bundler
  when: check_bundler_installed.rc != 0
  args:
    executable: /bin/bash
  become_user: ec2-user

- name: Initialize rbenv and install Rails
  shell: |
    source /home/ec2-user/.bash_profile
    bundle exec gem install rails -v {{ rails_version }}
  args:
    chdir: "{{ sample_app_dir }}"
    executable: /bin/bash
  become_user: ec2-user
  when: check_rails_installed.rc != 0





  