- name: check rails install
  shell: bash -lc "gem list -e rails | grep {{ rails_version }}"
  register: rails_installed
  changed_when: no
  ignore_errors: yes

- name: rails install
  gem: 
    name: rails
    version: "{{ rails_version }}"
    executable: /home/ec2-user/.rbenv/shims/gem
    user_install: no
  when: rails_installed is failed
  