- name: check bundler install
  shell: /home/ec2-user/.rbenv/shims/bundler --version
  register: check_bundler_installed
  changed_when: no
  ignore_errors: yes

- name: install bundler
  gem: 
    name: bundler
    version: "{{ bundler_version }}"
    executable: /home/ec2-user/.bash_profile
    permission: yes
    user_install: no
  when: check_bundler_installed is failed

- name: install gems
  shell: /home/ec2-user/.rbenv/shims/bundle install --path vendor/bundle
  args:
    chdir: "{{ sample_app_dir }}"
  become: yes
  become_user: ec2-user
  become_method: su
  become_flags: -s /bin/bash
  register: bundle_install
  changed_when: bundle_install.stdout.find('Installing') != -1
  ignore_errors: yes