- name: check rails install
  shell: source /home/ec2-user/.bash_profile && gem list -e rails | grep {{ rails_version }}
  register: check_rails_installed
  changed_when: no
  ignore_errors: yes

- name: install rails
  shell: source /home/ec2-user/.bash_profile && gem install rails -v {{ rails_version }}
  environment:
    PATH: "{{ ansible_env.PATH }}:/usr/local/bin"
  when: check_rails_installed.failed

