- name: Install specific version of Rails
  gem:
    name: rails
    version: "7.1.3.2"
    executable: /home/ec2-user/.rbenv/shims/gem
    user_install: no
  environment:
    PATH: "/home/ec2-user/.rbenv/shims:/usr/local/rbenv/bin:{{ ansible_env.PATH }}"


- name: Install Unicorn gem
  gem:
    name: unicorn
    executable: /home/ec2-user/.rbenv/shims/gem
    user_install: no
  environment:
    PATH: "/home/ec2-user/.rbenv/shims:/usr/local/rbenv/bin:{{ ansible_env.PATH }}"


- name: Check Ruby version
  command: bash -lc 'ruby -v'
  register: ruby_version
  environment:
    PATH: "/usr/local/rbenv/shims:/usr/local/rbenv/bin:{{ ansible_env.PATH }}"
  changed_when: false

- name: Ensure correct Ruby version is installed
  assert:
    that:
      - "'ruby 3.2.3' in ruby_version.stdout"
