- name: Ensure Gemfile exists
  stat:
    path: "{{ sample_app_dir }}/Gemfile"
  register: gemfile_check

- name: Install gems
  shell: bash -lc "bundle install"
  args:
    chdir: "{{ sample_app_dir }}"
  become_user: ec2-user
  when: gemfile_check.stat.exists

- name: Check if rails is installed
  shell: bash -lc "gem list -e rails | grep {{ rails_version }}"
  register: check_rails_installed
  changed_when: no
  ignore_errors: yes
  environment:
    RBENV_ROOT: /home/ec2-user/.rbenv
    PATH: /home/ec2-user/.rbenv/bin:/home/ec2-user/.rbenv/shims:{{ ansible_env.PATH }}

- name: Install Rails
  shell: bash -lc "bundle exec gem install rails -v {{ rails_version }}"
  args:
    chdir: "{{ sample_app_dir }}"
  become_user: ec2-user
  when: check_rails_installed.rc != 0

  