- name: Install specific version of Rails
  gem:
    name: rails
    version: "{{ rails_version }}"
    state: present
  environment:
    PATH: "/usr/local/rbenv/shims:/usr/local/rbenv/bin:{{ ansible_env.PATH }}"

- name: Install Unicorn
  gem:
    name: unicorn
    state: present
  environment:
    PATH: "/usr/local/rbenv/shims:/usr/local/rbenv/bin:{{ ansible_env.PATH }}"

- name: Check Ruby version
  command: bash -lc 'ruby -v'
  register: ruby_version
  environment:
    PATH: "/usr/local/rbenv/shims:/usr/local/rbenv/bin:{{ ansible_env.PATH }}"
  changed_when: false

- name: Ensure correct Ruby version is installed
  assert:
    that:
      - "'ruby 3.1.2' in ruby_version.stdout"
