- name: Check if Rails is installed
  command: bash -lc "gem list -i rails -v 7.1.3.2"
  register: rails_check
  ignore_errors: true
  become: true
  become_user: ec2-user

- name: Install Rails 7.1.3.2
  shell: bash -lc "gem install rails -v 7.1.3.2"
  when: rails_check.rc != 0
  become: true
  become_user: ec2-user
