- name: check rails install
  shell: bash -lc "gem list -e rails | grep {{ rails_version }}"
  register: check_rails_installed
  changed_when: no
  ignore_errors: yes

- name: install rails
  gem:
    name: rails
    version: "{{ rails_version }}"
    executable: "/usr/local/rbenv/shims:/usr/local/rbenv/bin:{{ ansible_env.PATH }}"
    user_install: no
  when: check_rails_installed.failed