- name: Ensure sample_app_dir exists
  file:
    path: "{{ sample_app_dir }}"
    state: directory
  become: yes

- name: Check if bundler is installed
  shell: /home/ec2-user/.rbenv/shims/bundler --version
  register: check_bundler_installed
  changed_when: no
  ignore_errors: yes

- name: Ensure Gemfile exists
  stat:
    path: "{{ sample_app_dir }}/Gemfile"
  register: gemfile_check

- name: Install gems
  shell: bash -lc "bundle install"
  args:
    chdir: "{{ sample_app_dir }}"
  become: yes
  become_user: ec2-user
  when: gemfile_check.stat.exists

- name: Check if Rails is installed
  shell: bash -lc "gem list -e rails | grep {{ rails_version }}"
  register: rails_installed
  changed_when: false
  ignore_errors: yes
  environment:
    PATH: "/usr/local/rbenv/shims:/usr/local/rbenv/bin:{{ ansible_env.PATH }}"

- name: Install Rails
  shell: bash -lc "gem install rails -v {{ rails_version }}"
  when: rails_installed is failed
  environment:
    PATH: "/usr/local/rbenv/shims:/usr/local/rbenv/bin:{{ ansible_env.PATH }}"