- name: check rails install
  shell: source /home/ec2-user/.bash_profile && gem list -e rails | grep {{ rails_version }}
  register: check_rails_installed
  changed_when: no
  ignore_errors: yes

- name: install rails
  shell: source /home/ec2-user/.bash_profile && /usr/local/bin/gem install rails -v 7.0.4
  when: check_rails_installed.failed


