- name: Install Rails
  shell: |
    source /home/ec2-user/.bash_profile
    /home/ec2-user/.rbenv/shims/bundle exec gem install rails -v {{ rails_version }}
  args:
    chdir: "{{ sample_app_dir }}"
    executable: /bin/bash
  become: yes
  become_user: ec2-user
  when: bundle_install is succeeded
