- name: Check if Node.js Yum repo file exists
  stat:
    path: /etc/yum.repos.d/nodesource-el7.repo
  register: nodesource_repo

- name: Add Yum repo for Node.js
  become_user: root
  shell: "curl -fsSL https://rpm.nodesource.com/setup_14.x | sudo bash -"
  when: not nodesource_repo.stat.exists
  changed_when: false

- name: Install Node.js
  become_user: root
  yum:
    name: nodejs
    state: latest

- name: Check if Yarn Yum repo file exists
  stat:
    path: /etc/yum.repos.d/yarn.repo
  register: yarn_repo

- name: Add Yum repo for Yarn
  become_user: root
  shell: "curl -fsSL https://dl.yarnpkg.com/rpm/yarn.repo | sudo tee /etc/yum.repos.d/yarn.repo"
  when: not yarn_repo.stat.exists
  changed_when: false

- name: Install Yarn
  become_user: root
  yum:
    name: yarn
    state: latest
