# Application_Layer テンプレート
AWSTemplateFormatVersion: 2010-09-09
Description: Application_Layer Template

Parameters:
  RaiseTech:
    Type: String
    Default: RaiseTech
    Description: RaiseTech

Resources:
  RaiseTechEC21a:
    Type: AWS::EC2::Instance
    Properties:
      NetworkInterfaces:
        - SubnetId: !ImportValue PublicSubnet1a-RaiseTech
          GroupSet:
            - !ImportValue SGID-EC2
          DeviceIndex: 0
      InstanceType: t2.micro
      ImageId: ami-0af1df87db7b650f4
      Tags:
        - Key: Name
          Value: !Sub ${RaiseTech}EC21a
      KeyName: RaiseTech
  RaiseTechEC21c:
    Type: AWS::EC2::Instance
    Properties:
      NetworkInterfaces:
        - SubnetId: !ImportValue PublicSubnet1c-RaiseTech
          GroupSet:
            - !ImportValue SGID-EC2
          DeviceIndex: 0
      InstanceType: t2.micro
      ImageId: ami-0af1df87db7b650f4
      Tags:
        - Key: Name
          Value: !Sub ${RaiseTech}EC21c
      KeyName: RaiseTech

  RDSMasterUserSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: "RDSMasterUserSecret"
      Description: "Secret for RDS Master User"
      GenerateSecretString:
        SecretStringTemplate: '{"username":"admin"}'
        GenerateStringKey: "password"
        PasswordLength: 16
        ExcludeCharacters: '"@/\'

  RaiseTechRDS:
    Type: AWS::RDS::DBInstance
    Properties:
      AllocatedStorage : 20
      DBInstanceClass: db.t2.micro
      Port: 3306
      StorageType: gp2
      BackupRetentionPeriod: 7
      MasterUsername: admin
      MasterUserPassword: '{{resolve:secretsmanager:RDSMasterUserSecret:SecretString:password}}'
      DBInstanceIdentifier: RaiseTech-DB
      DBName: RaiseTechRDS
      Engine: mysql
      EngineVersion: 8.0
      DBSubnetGroupName: !Ref RaiseTechRDSSubnetGroup
      MultiAZ: true
      VPCSecurityGroups:
        - !ImportValue SGID-RDS

  RaiseTechRDSSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: "RaiseTechDBSubnetGroup"
      DBSubnetGroupName: RaiseTechRDSSubnetGroup
      SubnetIds:
        - !ImportValue PrivateSubnet1a-RaiseTechVPC
        - !ImportValue PrivateSubnet1c-RaiseTechVPC

  RaiseTechALB:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      IpAddressType: ipv4
      Name: RaiseTechALB
      Scheme: internet-facing
      SecurityGroups:
        - !ImportValue SGID-ALB
      Subnets:
        - !ImportValue PrivateSubnet1a-RaiseTechVPC
        - !ImportValue PrivateSubnet1c-RaiseTechVPC
      Tags:
        - Key: Name
          Value: !Sub ${RaiseTech}ALB

  ALBTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Name: ALBTargetGroup
      Port: 80
      Protocol: HTTP
      Targets:
        - Id:
            Ref: RaiseTechEC21a
          Port: 80
        - Id:
            Ref: RaiseTechEC21c
          Port: 80
      VpcId: !ImportValue RaiseTechVpc

  ALBListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      DefaultActions:
        - Type: forward
          TargetGroupArn:
            !Ref ALBTargetGroup
      LoadBalancerArn:
        !Ref RaiseTechALB
      Port: 80
      Protocol: HTTP


