AWSTemplateFormatVersion: '2010-09-09'
Description: S3 Bucket Template

Parameters:
  S3BucketName:
    Type: String
    Description: Name for the S3 bucket
    MinLength: 3
    Default: your-default-bucket-name

Resources:
  RaiseTechS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref S3BucketName
      AccessControl: Private
      PublicAccessBlockConfiguration:
        BlockPublicAcls: True
        BlockPublicPolicy: True
        IgnorePublicAcls: True
        RestrictPublicBuckets: True
      VersioningConfiguration:
        Status: Enabled

  S3FullAccessRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: S3FullAccessRole
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: S3FullAccessPolicy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action: s3:*
                Resource: "*"
  
  S3FullAccessPolicies:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: S3FullAccessPolicies
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action: s3:*
            Resource: "arn:aws:s3:::your-default-bucket-name/*"
      Roles:
        - !Ref S3FullAccessRole

  S3FullAccessInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      InstanceProfileName: S3FullAccessInstanceProfile
      Roles:
        - !Ref S3FullAccessRole