AWSTemplateFormatVersion: 2010-09-09
Description: Sample S3 Bucket Template

Parameters:
  S3BucketName:
    Type: AWS::S3::Bucket
    Description: Name for the S3 bucket
    MinLength: 3
    Default: your-default-bucket-name

Resources:
  SampleS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref S3BucketName
      AccessControl: Private
      PublicAccessBlockConfiguration:
        BlockPublicAcls: True
        BlockPublicPolicy: True
        IgnorePublicAcls: True
        RestrictPublicBuckets: True
      VersioningConfiguration:
        Status: Enabled
