AWSTemplateFormatVersion: 2010-09-09
Description: Security_Layer Template

Parameters:
  CIDRIP:
    Type: String
    Description: The CIDR IP for MyIP

Resources:
  SecurityGroupEC2:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: SecurityGroupEC2
      GroupName: SecurityGroupEC2
      SecurityGroupIngress:
        - IpProtocol: tcp
<<<<<<< HEAD
          FromPort: 22
          ToPort: 22
=======
          FromPort: 80
          ToPort: 80
>>>>>>> e830fd1699ecd785a92183f4c736d169b99df643
          SourceSecurityGroupId: !Ref SecurityGroupALB
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: !Ref CIDRIP
      Tags:
        - Key: Name
          Value: SecurityGroupEC2
      VpcId: !ImportValue RaiseTechVpc

  SecurityGroupRDS:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: SecurityGroupRDS
      GroupName: SecurityGroupRDS
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 3306
          ToPort: 3306
<<<<<<< HEAD
          CidrIp: 0.0.0.0/32
=======
          CidrIp: 0.0.0.0/0
>>>>>>> e830fd1699ecd785a92183f4c736d169b99df643
      Tags:
        - Key: Name
          Value: SecurityGroupRDS
      VpcId: !ImportValue RaiseTechVpc


  SecurityGroupALB:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: SecurityGroupALB
      GroupName: SecurityGroupALB
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: !Ref CIDRIP
      Tags:
        - Key: Name
          Value: SecurityGroupALB
      VpcId: !ImportValue RaiseTechVpc


Outputs:
  SecurityGroupEC2:
    Value: !Ref SecurityGroupEC2
    Export:
<<<<<<< HEAD
      Name: SecurityGroupEC2
=======
      Name: SGID-EC2
>>>>>>> e830fd1699ecd785a92183f4c736d169b99df643

  SecurityGroupRDS:
    Value: !Ref SecurityGroupRDS
    Export:
<<<<<<< HEAD
      Name: SecurityGroupRDS
=======
      Name: SGID-RDS
>>>>>>> e830fd1699ecd785a92183f4c736d169b99df643

  SecurityGroupALB:
    Value: !Ref SecurityGroupALB
    Export:
<<<<<<< HEAD
      Name: SecurityGroupALB
=======
      Name: SGID-ALB
>>>>>>> e830fd1699ecd785a92183f4c736d169b99df643
