- name: Check if Node.js Yum repo file exists
  stat:
    path: /etc/yum.repos.d/nodesource-el7.repo
  register: nodesource_repo

- name: Add Yum repo for Node.js
  become_user: root
  shell: "curl -fsSL https://rpm.nodesource.com/setup_14.x | sudo bash -"
  when: not nodesource_repo.stat.exists
  changed_when: false

- name: Install Node.js
  become_user: root
  yum:
    name: nodejs
    state: latest

- name: Install npm
  become_user: root
  yum:
    name: npm
    state: latest