- name: check if nodejs already installed
  stat:
    path: /usrbin/node
  register: nodejs_bin

- name: Install required packages
  yum:
    name: "{{ item }}"
    state: present
  loop:
    - curl
    - python3-distutils
  when: ansible_os_family == 'Debian'

- name: Download nvm install script
  get_url:
    url: https://raw.githubusercontent.com/nvm-sh/nvm/v0.38.0/install.sh
    dest: /tmp/install_nvm.sh
    mode: '0755'

- name: Run nvm install script
  command: bash /tmp/install_nvm.sh
  args:
    creates: /root/.nvm/nvm.sh

- name: Source nvm
  shell: |
    . /root/.nvm/nvm.sh
    nvm install node
  args:
    executable: /bin/bash

- name: install nodejs
  yum:
    name: nodejs
    state:  installed
  become: yes
  when: not nodejs_bin.stat.exists
  