---
- name: remove mariadb
  become: true
  yum:
    name: mariadb-server
    state: absent

- name: remove mysql-server
  become: yes
  yum:
    name: mysql-server
    state: absent

- name: install mysql repository
  become: yes
  yum:
    name: 'https://repo.mysql.com//mysql80-community-release-el7-11.noarch.rpm'
    state: present
  register: mysql_installed

- name: import gpg-key
  become: yes
  rpm_key:
    state: present
    key: https://repo.mysql.com/RPM-GPG-KEY-mysql-2022
  when: mysql_installed.changed

- name: install mysql-community-client
  become: yes
  yum:
    name: mysql-community-client
    state: present
  when: mysql_installed.changed

- name: install mysql-community-devel
  become: yes
  yum:
    name: mysql-community-devel
    state: present
  when: mysql_installed.changed
