---
- hosts: web_server
  remote_user: ec2-user
  become: yes

  vars:
    ansible_become_method: sudo
    sample_app_dir: /home/ec2-user/raisetech-live8-sample-app
    puma_config_file: "{{ sample_app_dir }}/config/puma.yml"
    puma_start_script: "{{ sample_app_dir }}/start_puma.sh"
    aws_alb_host : "{{ (lookup('env','AWS_ALB_HOST')) }}"
    aws_ec2_host : "{{ (lookup('env','AWS_EC2_HOST')) }}"
    aws_db_user: "{{ (lookup('env','AWS_DB_USER')) }}"
    aws_db_pw : "{{ (lookup('env','AWS_DB_PW')) }}"
    aws_db_host : "{{ (lookup('env','AWS_DB_HOST')) }}"
    aws_s3_bucket: "{{ (lookup('env','AWS_S3_BUCKET')) }}"

  roles:
    - general
    - node_yarn
    - ruby
    - nginx
    - mysql
    - setup_server
