- name: Check if puma.service.sample exists
  stat:
    path: /home/ec2-user/raisetech-live8-sample-app/samples/puma.service.sample
  register: puma_service_check

- name: Move puma.service
  become_user: root
  command: mv /home/ec2-user/raisetech-live8-sample-app/samples/puma.service.sample /etc/systemd/system/puma.service
  when: puma_service_check.stat.exists

- name: Check if puma.rb exists
  stat:
    path: /home/ec2-user/raisetech-live8-sample-app/config/puma.rb
  register: puma_check

- name: Generate puma.rb from template
  template:
    src: roles/08_app/templates/puma.rb.j2
    dest: /home/ec2-user/raisetech-live8-sample-app/config/puma.rb

- name: Change directory to your Rails app directory
  command: cd /home/ec2-user/raisetech-live8-sample-app/


- name: Change owner of the puma socket file
  ansible.builtin.command:
    cmd: chown nginx:nginx /home/ec2-user/raisetech-live8-sample-app/tmp/sockets/puma.sock
  become: yes

- name: Start Puma service
  become_user: root
  systemd:
    name: puma
    state: started

- name: Start nginx service
  become_user: root
  service:
    name: nginx
    state: started

- name: Enable nginx service
  become_user: root
  service:
    name: nginx
    enabled: yes