- name: Check if Nginx is installed
  command: nginx -v
  register: check_nginx_installed
  changed_when: false
  ignore_errors: true

- name: Install Nginx
  become: true
  shell: amazon-linux-extras install -y nginx1
  when: check_nginx_installed.rc != 0

- name: Create rails.conf
  become: true
  template:
    src: rails.conf.j2
    dest: "/etc/nginx/conf.d/rails.conf"
  notify:
    - Restart Nginx

- name: Start Nginx
  become: true
  systemd:
    name: nginx
    state: started
  when: check_nginx_installed.rc == 0 and (start_nginx is undefined or start_nginx.changed)

- name: Reload Nginx configuration
  systemd:
    name: nginx
    state: reloaded
  become: true
  when: rails_conf_changed is defined

- name: Check Nginx configuration
  command: nginx -t
  become: true
  register: nginx_check
  ignore_errors: true

- name: Restart Nginx if configuration is OK
  systemd:
    name: nginx
    state: restarted
  become: true
  when: nginx_check.stdout is search('configuration file /etc/nginx/nginx.conf test is successful')
  notify:
    - Restart Nginx

- name: Check if puma.service.sample exists
  stat:
    path: /home/ec2-user/raisetech-live8-sample-app/samples/puma.service.sample
  register: puma_service_check

- name: Move puma.service
  become_user: root
  command: mv /home/ec2-user/raisetech-live8-sample-app/samples/puma.service.sample /etc/systemd/system/puma.service
  when: puma_service_check.stat.exists

- name: Check if puma.rb exists
  stat:
    path: /home/ec2-user/raisetech-live8-sample-app/config/puma.rb
  register: puma_check

- name: Ensure config directory exists
  file:
    path: /home/ec2-user/raisetech-live8-sample-app/config
    state: directory
    owner: ec2-user
    group: ec2-user
    mode: '0755'

- name: Generate puma.rb from template
  template:
    src: roles/08_app/templates/puma.rb.j2
    dest: /home/ec2-user/raisetech-live8-sample-app/config/puma.rb

- name: Change directory to your Rails app directory
  command: cd /home/ec2-user/raisetech-live8-sample-app/

- name: Install Bundler
  shell: bash -lc "bundle install"
  args:
    chdir: /home/ec2-user/raisetech-live8-sample-app/

- name: Run bin/setup
  command: /home/ec2-user/.rbenv/shims/ruby bin/setup
  args:
    chdir: /home/ec2-user/raisetech-live8-sample-app/

- name: Start Puma service
  become_user: root
  systemd:
    name: puma
    state: started

