- name: Check if puma.service.sample exists
  stat:
    path: /home/ec2-user/raisetech-live8-sample-app/samples/puma.service.sample
  register: puma_service_check

- name: Move puma.service
  become: yes
  command: mv /home/ec2-user/raisetech-live8-sample-app/samples/puma.service.sample /etc/systemd/system/puma.service
  when: puma_service_check.stat.exists

- name: Check if puma.rb exists
  stat:
    path: /home/ec2-user/raisetech-live8-sample-app/config/puma.rb
  register: puma_check

- name: Generate puma.rb from template
  template:
    src: roles/08_app/templates/puma.rb.j2
    dest: /home/ec2-user/raisetech-live8-sample-app/config/puma.rb
  when: not puma_check.stat.exists

- name: Run bin/setup
  command: /home/ec2-user/.rbenv/versions/3.2.3/bin/bundle exec bin/setup
  args:
    chdir: /home/ec2-user/raisetech-live8-sample-app/

- name: Start Puma service
  become: yes
  systemd:
    name: puma
    state: started

- name: Enable Puma service
  become: yes
  systemd:
    name: puma
    enabled: yes

- name: Start nginx service
  become: yes
  service:
    name: nginx
    state: started

- name: Enable nginx service
  become: yes
  service:
    name: nginx
    enabled: yes
