- name: Run bin/setup
  command: bash -lc "source /home/ec2-user/.rbenv/bin/rbenv init - && bin/setup"
  args:
    chdir: /home/ec2-user/raisetech-live8-sample-app/


- name: Check if puma.service.sample exists
  stat:
    path: /home/ec2-user/raisetech-live8-sample-app/samples/puma.service.sample
  register: puma_service_check

- name: Move puma.service
  become: yes
  command: mv /home/ec2-user/raisetech-live8-sample-app/samples/puma.service.sample /etc/systemd/system/puma.service
  when: puma_service_check.stat.exists

- name: Check if puma.rb exists
  stat:
    path: /home/ec2-user/raisetech-live8-sample-app/config/puma.rb
  register: puma_check

- name: Generate puma.rb from template
  template:
    src: roles/08_app/templates/puma.rb.j2
    dest: /home/ec2-user/raisetech-live8-sample-app/config/puma.rb
  when: not puma_check.stat.exists

- name: Install bundler gem
  shell: . /home/ec2-user/.bash_profile && gem install bundler
  become: yes
  become_user: ec2-user

- name: puma permissions
  become: yes
  command: chown -R ec2-user:ec2-user /home/ec2-user/raisetech-live8-sample-app

- name: Install application dependencies
  become: yes
  shell: . /home/ec2-user/.bash_profile && cd /home/ec2-user/raisetech-live8-sample-app && bundle install
  become_user: ec2-user


- name: puma.service.j2
  template:
    src: roles/08_app/templates/puma.service.j2
    dest: /etc/systemd/system/puma.service


- name: Reload systemd daemon
  become: yes
  command: systemctl daemon-reload

- name: Start Puma service
  become: yes
  systemd:
    name: puma
    state: started

- name: Enable Puma service
  become: yes
  systemd:
    name: puma
    enabled: yes

- name: Change permissions of /home/ec2-user
  become_user: root
  file:
    path: /home/ec2-user
    mode: 0701

- name: create tmp/sockets
  become: true
  become_method: sudo
  become_user: root
  ansible.builtin.file:
    path: "{{ sample_app_dir }}/tmp/sockets"
    state: directory
    mode: "0755"
    owner: ec2-user

- name: create tmp/pids
  become: true
  become_method: sudo
  become_user: root
  ansible.builtin.file:
    path: "{{ sample_app_dir }}/tmp/pids"
    state: directory
    mode: "0755"
    owner: ec2-user

- name: Start Puma
  ansible.builtin.command:
    cmd: bundle exec puma -C config/puma.rb
    chdir: /home/ec2-user/raisetech-live8-sample-app

- name: Install nginx
  become_user: root
  command: amazon-linux-extras install nginx1 -y

- name: create rails.conf
  become_user: root
  template:
    src: roles/09_nginx/templates/rails.conf.j2
    dest: "/etc/nginx/rails.conf"

- name: create rails.d.conf
  become_user: root
  template:
    src: roles/09_nginx/templates/rails.conf.j2
    dest: "/etc/nginx/conf.d/rails.conf"

- name: add server_names_hash_bucket_size to http block in nginx.conf
  become_user: root
  ansible.builtin.lineinfile:
    path: /etc/nginx/rails.conf
    insertbefore: types_hash_max_size 4096;
    firstmatch: yes
    line: server_names_hash_bucket_size 128;

- name: Start nginx service
  become: yes
  service:
    name: nginx
    state: started

- name: Enable nginx service
  become: yes
  service:
    name: nginx
    enabled: yes
