- name: Check if puma.service.sample exists
  stat:
    path: /home/ec2-user/raisetech-live8-sample-app/samples/puma.service.sample
  register: puma_service_check

- name: Move puma.service
  become: yes
  command: mv /home/ec2-user/raisetech-live8-sample-app/samples/puma.service.sample /etc/systemd/system/puma.service
  when: puma_service_check.stat.exists

- name: Check if puma.rb exists
  stat:
    path: /home/ec2-user/raisetech-live8-sample-app/config/puma.rb
  register: puma_check

- name: Generate puma.rb from template
  template:
    src: roles/08_app/templates/puma.rb.j2  
    dest: /home/ec2-user/raisetech-live8-sample-app/config/puma.rb

- name: Ensure db/schema.rb is writable
  file:
    path: /home/ec2-user/raisetech-live8-sample-app/db/schema.rb
    owner: ec2-user
    group: ec2-user
    mode: '0664'

- name: Ensure tmp directory exists
  file:
    path: /home/ec2-user/raisetech-live8-sample-app/tmp
    state: directory
    owner: ec2-user
    group: ec2-user
    mode: '0755'

- name: Ensure restart.txt is writable
  file:
    path: /home/ec2-user/raisetech-live8-sample-app/tmp/restart.txt
    state: touch
    owner: ec2-user
    group: ec2-user
    mode: '0664'

- name: Install Bundler
  become: yes
  become_user: ec2-user
  shell: bash -lc "bundle install"
  args:
    chdir: /home/ec2-user/raisetech-live8-sample-app/

- name: Run bin/setup
  become: yes
  become_user: ec2-user
  command: /home/ec2-user/.rbenv/shims/ruby bin/setup
  args:
    chdir: /home/ec2-user/raisetech-live8-sample-app/

- name: Install Puma dependencies
  become: yes
  become_user: ec2-user
  shell: bash -lc "bundle install"
  args:
    chdir: /home/ec2-user/raisetech-live8-sample-app/

- name: Reload systemd to apply new puma service
  become: yes
  shell: sudo systemctl daemon-reload

- name: Start Puma service
  become: yes
  systemd:
    name: puma
    state: started

- name: Install nginx
  become: yes
  command: amazon-linux-extras install nginx1 -y

- name: Create rails.conf
  become: yes
  template:
    src: roles/09_nginx/templates/rails.conf.j2
    dest: "/etc/nginx/rails.conf"

- name: Create rails.d.conf
  become: yes
  template:
    src: roles/09_nginx/templates/rails.conf.j2
    dest: "/etc/nginx/conf.d/rails.conf"

- name: Add server_names_hash_bucket_size to http block in nginx.conf
  become: yes
  lineinfile:
    path: /etc/nginx/nginx.conf
    insertbefore: 'types_hash_max_size 4096;'
    line: 'server_names_hash_bucket_size 128;'

- name: Start nginx service
  become: yes
  service:
    name: nginx
    state: started

- name: Enable nginx service
  become: yes
  service:
    name: nginx
    enabled: yes