---
- name: Check if Nginx is installed
  ansible.builtin.command: nginx -v
  register: check_nginx_installed
  changed_when: false
  ignore_errors: true

- name: Install Nginx if not installed
  ansible.builtin.shell: amazon-linux-extras install -y nginx1
  become: true
  when: check_nginx_installed.rc != 0

- name: Create rails.conf for Nginx
  ansible.builtin.template:
    src: rails.conf.j2
    dest: "/etc/nginx/conf.d/rails.conf"
  become: true
  notify:
    - Restart Nginx

- name: Start or reload Nginx
  ansible.builtin.systemd:
    name: nginx
    state: started
  become: true
  when: check_nginx_installed.rc == 0 and (start_nginx is undefined or start_nginx.changed)

- name: Check Nginx configuration
  ansible.builtin.command: nginx -t
  register: nginx_check
  become: true
  ignore_errors: true

- name: Restart Nginx if configuration is OK
  ansible.builtin.systemd:
    name: nginx
    state: restarted
  become: true
  when: nginx_check.stdout is search('configuration file /etc/nginx/nginx.conf test is successful')
  notify:
    - Restart Puma

- name: Install Puma gem
  ansible.builtin.gem:
    name: puma
    state: present
    executable: /home/ec2-user/.rbenv/shims/gem
  become: true

- name: Create Puma service file
  ansible.builtin.copy:
    content: |
      [Unit]
      Description=Puma HTTP Server
      After=network.target

      [Service]
      Type=simple
      User=ec2-user
      WorkingDirectory=/home/ec2-user/raisetech-live8-sample-app
      ExecStart=/home/ec2-user/.rbenv/shims/puma -C /home/ec2-user/raisetech-live8-sample-app/config/puma.rb
      Restart=always

      [Install]
      WantedBy=multi-user.target
    dest: /etc/systemd/system/puma.service
  become_user: root
  notify:
    - Reload systemd

- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: yes

- name: Reset failed Puma service
  ansible.builtin.command: systemctl reset-failed puma.service
  become: true
  ignore_errors: true

- name: Enable and start Puma service
  ansible.builtin.systemd:
    name: puma.service
    state: started
    enabled: yes

- name: Start Puma service
  ansible.builtin.systemd:
    name: puma.service
    state: started

- name: Restart Puma service if needed
  ansible.builtin.systemd:
    name: puma.service
    state: restarted

- name: Check Puma service status
  ansible.builtin.command: systemctl status puma.service
  register: puma_status
  become: true
  ignore_errors: true

- name: Display Puma service status
  ansible.builtin.debug:
    var: puma_status.stdout

- name: Check Puma service journal logs
  ansible.builtin.command: journalctl -xe -u puma.service
  register: puma_journal
  become: true
  ignore_errors: true

- name: Display Puma service journal logs
  ansible.builtin.debug:
    var: puma_journal.stdout
