- name: Check if Bundler is installed
  become_user: ec2-user
  stat:
    path: /home/ec2-user/.rbenv/versions/3.2.3/bin/bundle
  register: bundler_check

- name: Install Bundler
  become_user: ec2-user
  command: bash -lc "gem install bundler"