- name: Check if Bundler is installed
  stat:
    path: /home/ec2-user/.rbenv/versions/3.2.3/bin/bundle
  register: bundler_check

- name: Install Bundler
  command: bash -lc "source /home/ec2-user/.rbenv/bin/rbenv init - && gem install bundler"
  when: not bundler_check.stat.exists
  args:
    chdir: /home/ec2-user/raisetech-live8-sample-app/
