---
- name: Ensure sample_app_dir exists
  file:
    path: "{{ sample_app_dir }}"
    state: directory
  become: yes

- name: Check if bundler is installed
  shell: /home/ec2-user/.rbenv/shims/bundler --version
  register: check_bundler_installed
  changed_when: no
  ignore_errors: yes

- name: Install bundler
  gem: 
    name: bundler
    version: "{{ bundler_version }}"
    executable: /home/ec2-user/.rbenv/shims/gem
    user_install: no
  when: check_bundler_installed is failed

- name: Install gems with bundler
  shell: bash -lc "source ~/.bash_profile && /home/ec2-user/.rbenv/shims/bundle install"
  args:
    chdir: "{{ sample_app_dir }}"
  when: check_bundler_installed is failed or not was_cloned_rails.stat.exists or has_directory_gemfile.stat.exists
