- name: check bundler 2.3.14 installed 1
  shell:  bash -lc "bundler -v| grep {{ bundler_version }}"
  register: has_bundler_1
  changed_when: False
  ignore_errors: yes

- name: update bundler
  shell: bash -lc "gem install bundler -v {{ bundler_version }}"
  args:
    chdir: "{{ sample_app_dir }}"
  when: has_bundler_1.failed

- name: check bundler installed
  shell: bash -lc "bundle -v | grep {{ bundler_version }}"
  register: bundler_version_check
  changed_when: False

- name: install gems
  shell: bash -lc "bundle install"
  args:
    chdir: "{{ sample_app_dir }}"
  when: not was_cloned_rails.stat.exists or has_directory_gemfile.stat.exists

- name: install webpacker
  shell: bash -lc "bundle exec rails webpacker:install"
  args:
    chdir: "{{ sample_app_dir }}"
  when: not was_cloned_rails.stat.exists or has_directory_gemfile.stat.exists
