- name: Check if Yarn Yum repo file exists
  stat:
    path: /etc/yum.repos.d/yarn.repo
  register: yarn_repo

- name: Add Yum repo for Yarn
  become_user: root
  shell: "curl -fsSL https://dl.yarnpkg.com/rpm/yarn.repo | sudo tee /etc/yum.repos.d/yarn.repo"
  when: not yarn_repo.stat.exists
  changed_when: false

- name: Install Yarn
  become_user: root
  yum:
    name: yarn
    state: latest