- name: check yarn install
  ansible.builtin.command: yarn --version
  register: yarn_exists
  changed_when: no
  ignore_errors: true

- name: yarn install
  ansible.builtin.command: bash -lc "npm install --global yarn"
  when: yarn_exists is failed

- name: check yarn install version
  ansible.builtin.command: bash -lc "yarn --version  | grep {{ yarn_version }}"
  register: yarn_exists_wedefined_version
  changed_when: no
  ignore_errors: true

- name: set yarn version
  ansible.builtin.command: bash -lc "yarn set version {{ yarn_version }}"
  when: yarn_exists_wedefined_version is failed