---
- name: check nginx exsits
  shell: bash -lc "nginx -v"
  register: nginx_exists
  changed_when: no
  ignore_errors: yes

- name: nginx install
  become: yes
  shell: bash -lc "amazon-linux-extras install -y nginx1"
  when: nginx_exists is failed

- name: create default.conf
  become: yes
  template:
    src: default.conf.j2
    dest: /etc/nginx/conf.d/default.conf
  when: nginx_exists is failed

- name: nginx permission
  become: yes
  file: 
    path: /var/lib
    state: directory
    mode: '0775'
    recurse: yes
  when: nginx_exists is failed

- name: edit puma.service
  become: yes
  template:
    src: puma.service.j2
    dest: /etc/systemd/system/puma.service

- name: puma permission
  become: yes
  file: 
    path: /etc/systemd
    state: directory
    mode: '0775'
    recurse: yes

- name: reload puma.service
  become: yes
  shell: |
    systemctl daemon-reload
- name: reload puma.service
  become: yes
  shell: |
    systemctl enable puma.service
- name: create tmp/sockets
  become: yes
  ansible.builtin.file:
    path: "{{ app_dir }}/tmp/sockets"
    state: directory
    mode: "0755"
    owner: ec2-user

- name: create tmp/pids
  become: yes
  ansible.builtin.file:
    path: "{{ app_dir }}/tmp/pids"
    state: directory
    mode: "0755"
    owner: ec2-user

- name: restart server nginx
  become: yes
  shell: |
    systemctl restart nginx
  args:
    chdir: "{{ app_dir }}"

- name: restart server puma
  become: yes
  shell: |
    systemctl restart puma
  args:
    chdir: "{{ app_dir }}"
