- name: Clone rbenv repository
  become_user: root
  git:
    repo: "https://github.com/sstephenson/rbenv.git"
    dest: "/home/ec2-user/.rbenv"
    version: master

- name: Change ownership of .rbenv directory to ec2-user
  become_user: root
  file:
    path: "/home/ec2-user/.rbenv"
    owner: ec2-user
    group: ec2-user
    recurse: yes
    state: directory

- name: Add rbenv path to .bash_profile
  lineinfile:
    path: /home/ec2-user/.bash_profile
    line: 'export PATH="$HOME/.rbenv/bin:$PATH"'
    create: yes

- name: Initialize rbenv
  lineinfile:
    path: /home/ec2-user/.bash_profile
    line: 'eval "$(rbenv init -)"'
    create: yes

- name: Add rbenv path to .bash_profile
  lineinfile:
    path: /home/ec2-user/.bash_profile
    line: 'export PATH="$HOME/.rbenv/bin:$PATH"'
    create: yes

- name: Load .bash_profile
  shell: bash -lc "source /home/ec2-user/.bash_profile"

- name: Install rbenv plugins
  git:
    repo: https://github.com/sstephenson/ruby-build.git
    dest: "/home/ec2-user/.rbenv/plugins/ruby-build"

- name: Check if Ruby is installed
  stat:
    path: /home/ec2-user/.rbenv/versions/3.1.2
  register: ruby_check

- name: Install Ruby 3.1.2
  shell: bash -lc "rbenv install 3.1.2"
  when: not ruby_check.stat.exists

- name: Rehash rbenv
  shell: bash -lc "rbenv rehash"

- name: Set global Ruby version to 3.1.2
  shell: bash -lc "rbenv global 3.1.2"