- name: Clone rbenv repository
  git:
    repo: 'https://github.com/rbenv/rbenv.git'
    dest: '/home/ec2-user/.rbenv'
    version: master
    update: no
  become_user: ec2-user

- name: Clone ruby-build repository
  git:
    repo: 'https://github.com/rbenv/ruby-build.git'
    dest: '/home/ec2-user/.rbenv/plugins/ruby-build'
    version: master
    update: no
  become_user: ec2-user

- name: Add rbenv to bash_profile
  lineinfile:
    path: /home/ec2-user/.bash_profile
    line: 'export PATH="$HOME/.rbenv/bin:$PATH"'
    create: yes
  become_user: ec2-user

- name: Add rbenv init to bash_profile
  lineinfile:
    path: /home/ec2-user/.bash_profile
    line: 'eval "$(rbenv init -)"'
    create: yes
  become_user: ec2-user

- name: Initialize rbenv
  shell: |
    export RBENV_ROOT="${HOME}/.rbenv"
    export PATH="${RBENV_ROOT}/bin:${PATH}"
    eval "$(rbenv init -)"
    rbenv rehash
  become_user: ec2-user
  changed_when: false

- name: Install Ruby
  shell: |
    export RBENV_ROOT="${HOME}/.rbenv"
    export PATH="${RBENV_ROOT}/bin:${PATH}"
    eval "$(rbenv init -)"
    rbenv install {{ ruby_version }}
    rbenv global {{ ruby_version }}
  become_user: ec2-user

- name: Check if bundler is installed
  shell: /home/ec2-user/.rbenv/shims/bundler --version
  register: check_bundler_installed
  changed_when: no
  ignore_errors: yes

- name: Install bundler
  gem:
    name: bundler
    version: "{{ bundler_version }}"
    executable: /home/ec2-user/.rbenv/shims/gem
    user_install: no
  when: check_bundler_installed is failed

- name: Ensure Gemfile exists
  stat:
    path: "{{ sample_app_dir }}/Gemfile"
  register: gemfile_check

- name: Install gems
  shell: bash -lc "bundle install"
  args:
    chdir: "{{ sample_app_dir }}"
  become_user: ec2-user
  when: gemfile_check.stat.exists

- name: Check if rails is installed
  shell: bash -lc "gem list -e rails | grep {{ rails_version }}"
  register: check_rails_installed
  changed_when: no
  ignore_errors: yes
  environment:
    RBENV_ROOT: /home/ec2-user/.rbenv
    PATH: /home/ec2-user/.rbenv/bin:/home/ec2-user/.rbenv/shims:{{ ansible_env.PATH }}

- name: Install rails
  shell: bash -lc "gem install rails -v {{ rails_version }}"
  when: check_rails_installed.failed
  become_user: ec2-user
  environment:
    RBENV_ROOT: /home/ec2-user/.rbenv
    PATH: /home/ec2-user/.rbenv/bin:/home/ec2-user/.rbenv/shims:{{ ansible_env.PATH }}