- name: Install rbenv
  git:
    repo: 'https://github.com/rbenv/rbenv.git'
    dest: '~/.rbenv'
    version: master
  become_user: ec2-user

- name: Add rbenv to bashrc
  lineinfile:
    path: /home/ec2-user/.bashrc
    line: 'export PATH="$HOME/.rbenv/bin:$PATH"'
    insertafter: EOF
  become_user: ec2-user

- name: Initialize rbenv
  lineinfile:
    path: /home/ec2-user/.bashrc
    line: 'eval "$(rbenv init -)"'
    insertafter: EOF
  become_user: ec2-user

- name: Install ruby-build as an rbenv plugin
  git:
    repo: 'https://github.com/rbenv/ruby-build.git'
    dest: '~/.rbenv/plugins/ruby-build'
    version: master
    force: yes
  become_user: ec2-user

- name: Install Ruby
  command: /home/ec2-user/.rbenv/bin/rbenv install 3.2.3
  args:
    creates: /home/ec2-user/.rbenv/versions/3.2.3
  become_user: ec2-user

- name: Set global Ruby version
  command: /home/ec2-user/.rbenv/bin/rbenv global 3.2.3
  become_user: ec2-user