- name: install rbenv
  git:
    repo: https://github.com/sstephenson/rbenv.git
    dest: "{{ sample_app_dir }}/.rbenv"
  when: has_rbenv is failed

- name: install ruby-build
  git:
    repo: https://github.com/sstephenson/ruby-build.git
    dest: "{{ sample_app_dir }}/.rbenv/plugins/ruby-build"
  when: has_ruby_build is failed

- name: register path and update bash
  shell:  |
    echo 'export PATH="$HOME/.rbenv/bin:$PATH"' >> ~/.bash_profile;
    echo 'export PATH="$HOME/.rbenv/plugins/ruby-build/bin:$PATH"' >> ~/.bash_profile;
    echo 'eval "$(rbenv init -)"' >> ~/.bash_profile;
    source {{ sample_app_dir }}/.bash_profile;
    rbenv rehash;
  when: has_rbenv is failed

- name: ruby install
  shell:  bash -lc "rbenv install {{ ruby_version }}"
  when: has_ruby_version is failed

- name: ruby set global
  shell:  bash -lc "rbenv global {{ ruby_version }}"
  when: has_ruby_version is failed