- name: check rbenv install
  shell: bash -lc "rbenv --version"
  register: check_rbenv_installed
  changed_when: no
  ignore_errors: yes

- name: install rbenv
  git:
    repo: https://github.com/rbenv/rbenv.git
    dest: /home/ec2-user/.rbenv
  when: check_rbenv_installed.rc != 0

- name: Add rbenv to PATH
  lineinfile:
    path: /home/ec2-user/.bash_profile
    line: 'export PATH="$HOME/.rbenv/bin:$PATH"'
  when: check_rbenv_installed.rc != 0

- name: eval rbenv init
  lineinfile:
    path: /home/ec2-user/.bash_profile
    line: 'eval "$(rbenv init --no-rehash -)"'
  when: check_rbenv_installed.rc != 0

- name: load .bash_profile
  shell: bash -lc "source ~/.bash_profile"
  when: check_rbenv_installed.rc != 0


# ruby------------------------------------------------------------
- name: install ruby-build
  git:
    repo: https://github.com/rbenv/ruby-build.git
    dest: /home/ec2-user/.rbenv/plugins/ruby-build
  when: check_rbenv_installed.rc != 0

- name: install ruby
  shell: bash -lc "rbenv install {{ ruby_version }}"
  args:
    executable: /bin/bash
  when: check_rbenv_installed.rc != 0

- name: rehash rbenv
  shell: bash -lc "rbenv rehash"
  when: check_rbenv_installed.rc != 0

- name: set default ruby version
  shell: bash -lc "rbenv global {{ ruby_version }}"
  when: check_rbenv_installed.rc != 0

