- name: Check rbenv install
  shell: bash -lc "rbenv --version"
  register: check_rbenv_installed
  changed_when: no
  ignore_errors: yes

- name: Install rbenv
  git:
    repo: https://github.com/rbenv/rbenv.git
    dest: /home/ec2-user/.rbenv
  when: check_rbenv_installed.failed

- name: Add rbenv to PATH
  lineinfile:
    path: /home/ec2-user/.bash_profile
    line: 'export PATH="$HOME/.rbenv/bin:$PATH"'
    create: yes
  when: check_rbenv_installed.failed

- name: eval rbenv init
  lineinfile:
    path: /home/ec2-user/.bash_profile
    line: 'eval "$(rbenv init -)"'
    create: yes
  when: check_rbenv_installed.failed

- name: Load .bash_profile
  shell: bash -lc "source ~/.bash_profile"
  when: check_rbenv_installed.failed

- name: Install ruby-build
  git:
    repo: https://github.com/rbenv/ruby-build.git
    dest: /home/ec2-user/.rbenv/plugins/ruby-build
  when: check_rbenv_installed.failed

- name: Load .bash_profile after installing ruby-build
  shell: bash -lc "source ~/.bash_profile"
  when: check_rbenv_installed.failed

- name: Recheck rbenv install
  shell: bash -lc "rbenv --version"
  register: recheck_rbenv_installed
  changed_when: no
  ignore_errors: yes

- name: Install Ruby
  shell: bash -lc "rbenv install {{ ruby_version }}"
  args:
    executable: /bin/bash
  environment:
    PATH: "/home/ec2-user/.rbenv/bin:/home/ec2-user/.rbenv/shims:{{ ansible_env.PATH }}"
  when: recheck_rbenv_installed.rc == 0

- name: Rehash rbenv
  shell: bash -lc "rbenv rehash"
  when: recheck_rbenv_installed.rc == 0

- name: Set default Ruby version
  shell: bash -lc "rbenv global {{ ruby_version }}"
  when: recheck_rbenv_installed.rc == 0
