- name: Install rbenv
  git:
    repo: 'https://github.com/rbenv/rbenv.git'
    dest: '~/.rbenv'
    version: master
  become_user: ec2-user

- name: Add rbenv to bashrc
  lineinfile:
    path: /home/ec2-user/.bashrc
    line: 'export PATH="$HOME/.rbenv/bin:$PATH"'
    insertafter: EOF
  become_user: ec2-user

- name: Initialize rbenv
  lineinfile:
    path: /home/ec2-user/.bashrc
    line: 'eval "$(rbenv init -)"'
    insertafter: EOF
  become_user: ec2-user

- name: Add the application directory to Git safe.directory
  ansible.builtin.command: git config --global --add safe.directory /home/ec2-user/raisetech-live8-sample-app
  become: yes
  become_user: ec2-user

- name: Clone the sample app repository
  ansible.builtin.git:
    repo: 'https://github.com/yuta-ushijima/raisetech-live8-sample-app.git'
    dest: /home/ec2-user/raisetech-live8-sample-app
    version: master
    force: yes
  become_user: ec2-user

- name: Change directory
  shell: cd raisetech-live8-sample-app

- name: Install Ruby
  command: /home/ec2-user/.rbenv/bin/rbenv install 3.2.3
  args:
    creates: /home/ec2-user/.rbenv/versions/3.2.3
  become_user: ec2-user

- name: Set global Ruby version
  command: /home/ec2-user/.rbenv/bin/rbenv global 3.2.3
  become_user: ec2-user