- name: Ensure rbenv directory is absent
  file:
    path: /root/.rbenv
    state: absent
  become: yes

- name: Clone rbenv repository
  git:
    repo: 'https://github.com/rbenv/rbenv.git'
    dest: '/root/.rbenv'
    update: no
  become: yes

- name: Add rbenv to PATH and initialize it
  lineinfile:
    dest: /root/.bash_profile
    regexp: 'export PATH="\$HOME/.rbenv/bin:\$PATH"'
    line: 'export PATH="$HOME/.rbenv/bin:$PATH"'
  become: yes

- name: Add rbenv init to bash_profile
  lineinfile:
    dest: /root/.bash_profile
    regexp: 'eval "\$\(rbenv init -\)"'
    line: 'eval "$(rbenv init -)"'
  become: yes

- name: Source bash_profile
  shell: 'source /root/.bash_profile'
  args:
    executable: /bin/bash
  become: yes

- name: Clone ruby-build repository
  git:
    repo: 'https://github.com/rbenv/ruby-build.git'
    dest: '/root/.rbenv/plugins/ruby-build'
    update: no
  become: yes

- name: Install Ruby 3.1.2
  shell: bash -lc "rbenv install 3.1.2 && rbenv global 3.1.2"
  become: yes

- name: Install Bundler
  shell: bash -lc "gem install bundler && rbenv rehash"
  become: yes

- name: Verify Ruby installation
  shell: bash -lc "ruby -v"
  register: ruby_version
  become: yes

- debug:
    msg: "Ruby version: {{ ruby_version.stdout }}"

- name: Verify Bundler installation
  shell: bash -lc "bundler -v"
  register: bundler_version
  become: yes

- debug:
    msg: "Bundler version: {{ bundler_version.stdout }}"