- name: Clone rbenv repository
  git:
    repo: 'https://github.com/rbenv/rbenv.git'
    dest: '/home/ec2-user/.rbenv'
    version: master
    update: no
  become_user: ec2-user

- name: Clone ruby-build repository
  git:
    repo: 'https://github.com/rbenv/ruby-build.git'
    dest: '/home/ec2-user/.rbenv/plugins/ruby-build'
    version: master
    update: no
  become_user: ec2-user

- name: Add rbenv to bash_profile
  lineinfile:
    path: /home/ec2-user/.bash_profile
    line: 'export PATH="$HOME/.rbenv/bin:$PATH"'
    create: yes
  become_user: ec2-user

- name: Add rbenv init to bash_profile
  lineinfile:
    path: /home/ec2-user/.bash_profile
    line: 'eval "$(rbenv init -)"'
    create: yes
  become_user: ec2-user

- name: Initialize rbenv
  shell: |
    export RBENV_ROOT="${HOME}/.rbenv"
    export PATH="${RBENV_ROOT}/bin:${PATH}"
    eval "$(rbenv init -)"
    rbenv rehash
  become_user: ec2-user
  changed_when: false

- name: Install Ruby
  shell: |
    export RBENV_ROOT="${HOME}/.rbenv"
    export PATH="${RBENV_ROOT}/bin:${PATH}"
    eval "$(rbenv init -)"
    rbenv install {{ ruby_version }}
    rbenv global {{ ruby_version }}
  become_user: ec2-user

