- name: Clone rbenv repository
  git:
    repo: "git remote set-url origin git@github.com:sstephenson/rbenv.git"
    dest: "/home/ec2-user/.rbenv"
    version: master
  become_user: ec2-user

- name: Change ownership of .rbenv directory to ec2-user
  become: yes
  file:
    path: "/home/ec2-user/.rbenv"
    owner: ec2-user
    group: ec2-user
    recurse: yes
    state: directory

- name: Add rbenv paths and initialize rbenv in .bash_profile
  become: yes
  lineinfile:
    path: /home/ec2-user/.bash_profile
    line: |
      export PATH="$HOME/.rbenv/bin:$PATH"
      eval "$(rbenv init -)"
    create: yes

- name: Load .bash_profile
  shell: . /home/ec2-user/.bash_profile
  become: yes
  args:
    executable: /bin/bash

- name: Install rbenv plugins
  become: yes
  git:
    repo: https://github.com/sstephenson/ruby-build.git
    dest: "/home/ec2-user/.rbenv/plugins/ruby-build"
  become_user: ec2-user

- name: Check if Ruby 3.2.3 is installed
  stat:
    path: /home/ec2-user/.rbenv/versions/3.2.3
  register: ruby_check

- name: Install Ruby 3.2.3
  shell: . /home/ec2-user/.bash_profile && rbenv install 3.2.3
  become: yes
  become_user: ec2-user
  when: not ruby_check.stat.exists

- name: Rehash rbenv
  shell: . /home/ec2-user/.bash_profile && rbenv rehash
  become: yes
  become_user: ec2-user

- name: Set global Ruby version to 3.2.3
  shell: . /home/ec2-user/.bash_profile && rbenv global 3.2.3
  become: yes
  become_user: ec2-user
