- name: Clone rbenv repository
  become_user: ec2-user
  git:
    repo: "https://github.com/sstephenson/rbenv.git"
    dest: "/home/ec2-user/.rbenv"
    version: master

- name: Change ownership of .rbenv directory to ec2-user
  become_user: ec2-user
  file:
    path: "/home/ec2-user/.rbenv"
    owner: ec2-user
    group: ec2-user
    recurse: yes
    state: directory

- name: Add rbenv path to .bash_profile
  become_user: ec2-user
  lineinfile:
    path: /home/ec2-user/.bash_profile
    line: 'export PATH="$HOME/.rbenv/bin:$PATH"'
    create: yes

- name: Initialize rbenv
  become_user: ec2-user
  lineinfile:
    path: /home/ec2-user/.bash_profile
    line: 'eval "$(rbenv init -)"'
    create: yes

- name: Add rbenv path to .bash_profile
  become_user: ec2-user
  lineinfile:
    path: /home/ec2-user/.bash_profile
    line: 'export PATH="$HOME/.rbenv/bin:$PATH"'
    create: yes

- name: Load .bash_profile
  become_user: ec2-user
  shell: bash -lc "source /home/ec2-user/.bash_profile"

- name: Install rbenv plugins
  become_user: ec2-user
  git:
    repo: https://github.com/sstephenson/ruby-build.git
    dest: "/home/ec2-user/.rbenv/plugins/ruby-build"


- name: Check if Ruby is installed
  become_user: ec2-user
  stat:
    path: /home/ec2-user/.rbenv/versions/3.2.3
  register: ruby_check

- name: Install Ruby 3.2.3
  become_user: ec2-user
  shell: bash -lc "rbenv install 3.2.3"
  when: not ruby_check.stat.exists

- name: Rehash rbenv
  become_user: ec2-user
  shell: bash -lc "rbenv rehash"

- name: Set global Ruby version to 3.2.3
  become_user: ec2-user
  shell: bash -lc "rbenv global 3.2.3"